[project]
name = "google-adk-commentator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "certifi>=2025.6.15",
    "google-adk>=1.5.0",
    "litellm>=1.74.0",
    "loguru>=0.7.3",
    "pyaudio>=0.2.14",
]
